### ISSUE TITLE
Питання щодо 2 Етапу курсової роботи

### ISSUE THREAD

**Issue by Nadiia-Shchur** [anrom7/CL_project_2015#10]
Доброї ночі!
На 2 етапі курсової роботи, а саме у пункті 4, де ми маємо перевіряти результати зняття омонімії в роботах попереднього курсу, ми зіштовхнулись з  проблемою: 
- деякі файли попереднього курсу відкриваються у стилі "аля арабіка" )))) . Ми так розуміємо, що кодування, мабуть неправильне, або що... Документ зовсім не можливо прочитати. 
  Що нам робити в такому випадку, коли це твій варіант, а його не то що перевірити, його прочитати не можна....

Дякую.

**Comment by anrom7** [comment]
Надсилаєте прізвище, яке є у назві файла де є проблеми з кодуванням і я вам надсилаю файл з виправленим кодуванням.

**Comment by KhrystynaRybchak** [comment]
Добрий день!
Потапенко
Файлу ..._without_h немає.
Файл ..._morph у неправильному кодуванні.
Дякую)

**Comment by anrom7** [comment]
Кдування змінив. Зніміть омонімію в тому що є _morph

**Comment by KhrystynaRybchak** [comment]
Добрий вечір!
Кілька питань)
1. Чи вважати омонімією відмінки, яких вимагає прийменник?
Наприклад, "за"  prep:rv_rod:rv_zna:rv_oru
Залишати без змін чи тільки той відмінок, якого вимагає прийменник у конкретному випадку?
"за репутацію"   prep:rv_zna
2. Підкажіть, де файл _morph із зміненим кодуванням?)

**Comment by anrom7** [comment]
1)тільки той відмінок, якого вимагає прийменник у конкретному випадку
2) в CL_project в гілці Потапенко

**Comment by KhrystynaRybchak** [comment]
Але єдиний файл _morph у гілці Потапенко і далі відкривається незрозуміло.

**Comment by anrom7** [comment]
а тепер спробуйте

10 жовтня 2015 р. 18:25 KhrystynaRybchak notifications@github.com написав:

> Але єдиний файл _morph у гілці Потапенко і далі відкривається незрозуміло.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/anrom7/CL_project_2015/issues/10#issuecomment-147100092
> .

﻿                 SENT_START 

Не            не              part 
надійний    надійний        adj:m:v_naz:compb 
ресторан    ресторан        noun:m:v_naz 
!                            - 
                    SENT_END 

```
                SENT_START 
```

скарг      скарга            noun:p:v_rod 
,           -                   - 
берутся      -                   - 
уваги      увага          noun:f:v_rod 
ВЗАГАЛІ      взагалі      adv:v-u 
!               - 
                    SENT_END 

```
                SENT_START 
```

Домовленостей  домовленість noun:p:v_rod 
дотримуються    дотримуватися verb:rev:pres:p:3:imperf
адміністрацією    адміністрація noun:f:v_oru 
ресторану      ресторан      noun:m:v_dav 
!   - 
                    SENT_END 
                    SENT_START 
обману    обманути обман     verb:futr:s:1:perf noun:m:v_dav noun:m:v_mis noun:m:v_rod 
брехні    брехня            noun:f:v_dav noun:f:v_mis noun:f:v_rod 
замилювання  замилювання noun:n:v_naz noun:n:v_rod noun:n:v_zna 
очей    око          noun:p:v_rod 
складається  складатися   verb:rev:pres:s:3:imperf
дуже    дуже дужий      adv adj:n:v_naz:compb adj:n:v_zna:compb 
хороша    хороший        adj:f:v_naz:compb 
картина  картина           noun:f:v_naz 
ресторації    ресторація noun:f:v_dav noun:f:v_mis noun:f:v_rod noun:p:v_naz noun:p:v_zna 
,   - - 
"   - - 
ресторація    ресторація noun:f:v_naz 
"   - - 
гучно  гучно          adv:compb 
сказано  сказати        verb:impers:perf 
!   - 
                        SENT_END 
                        SENT_START 
кінцевому  кінцевий        adj:m:v_dav adj:m:v_mis adj:n:v_dav adj:n:v_mis 
,   - - 
власники    власник  noun:p:v_kly:anim noun:p:v_naz:anim 
ресторану  ресторан    noun:m:v_dav noun:m:v_mis noun:m:v_rod 
приймають  приймати    verb:pres:p:3:imperf 
рішення  рішення      noun:n:v_naz noun:n:v_rod 
домовленості    домовленість noun:f:v_dav noun:f:v_mis 
підписанні    підписання        noun:n:v_mis 
ДОГОВОРУ    договір  noun:m:v_dav noun:m:v_rod 
двох    двоє  два        numr:p:v_mis numr:p:v_rod numr:p:v_zna 
сторін    сторона      noun:p:v_rod 
,   - - 
роблять  робити            verb:pres:p:3:imperf 
вважають    вважати  verb:pres:p:3:imperf 
потрібне    потрібний  adj:n:v_naz:compb adj:n:v_zna:compb 
.   - 
                            SENT_END 
                            SENT_START 
Збільшують    збільшувати  verb:pres:p:3:imperf 
мін  міна                    noun:p:v_rod 
суму    сум сума             noun:m:v_dav noun:m:v_mis noun:m:v_rod 
замовлення    замовлення noun:n:v_naz noun:n:v_rod noun:n:v_zna 
особу  особа              noun:f:v_zna:anim 
,   -   - 
обманюють  обманювати        verb:pres:p:3:imperf 
рахунок  рахунок          noun:m:v_naz noun:m:v_zna 
кількості  кількість      noun:f:v_dav noun:f:v_mis 
місць  місце              noun:p:v_rod 
"   - - 
йдеться  йтися              verb:rev:pres:s:3:imperf
весілля  весілля      noun:n:v_naz noun:n:v_rod noun:n:v_zna 
"   - - 
.   - 
                            SENT_END
                            SENT_START 
раджу  раджа радити         noun:f:v_zna:anim verb:pres:s:1:imperf 
відвідувати  відвідувати  verb:inf:imperf 
"   - - 
ГЕНДЕЛИК-РЕСТОРАН   - - 
"   - - 
.   - 
                            SENT_END 
                            SENT_START 
місті  місто          noun:n:v_mis 
Івано-Франківськ Івано-Франківськ noun:m:v_naz noun:m:v_zna 
ліч  - - 
на    на                prep:rv_zna:rv_mis 
затишніших    затишний    adj:p:v_mis:compr adj:p:v_rod:compr 
фінансово  фінансово  adv 
вигідніших    вигідний    adj:p:v_mis:compr adj:p:v_rod:compr 
,   - - 
справжніх  справжній  adj:p:v_mis adj:p:v_rod  
ресторанів    ресторан    noun:p:v_rod 
!   - 
                            SENT_END 
                            SENT_START 
Єдине  єдиний        adj:n:v_naz adj:n:v_zna 
,   - - 
ресторан    ресторан    noun:m:v_naz noun:m:v_zna 
"   - - 
Рів'єра   - - 
"   - - 
пригостити    пригостити    verb:inf:perf 
ХОРОШОЮ  хороший  adj:f:v_oru:compb 
ФІРМОВОЮ    фірмовий adj:f:v_oru 
"   - - 
ЛАПШОЮ    - - 
"   - - 
,   - - 
яку  як який noun:m:v_dav:anim noun:m:v_mis:anim dj:f:v_zna:&pron:int:rel:def
адміністратор  адміністратор noun:m:v_naz:anim 
самотужки  самотужки adv 
повісить    повісити verb:futr:s:3:perf 
вуха    вухо noun:n:v_rod noun:p:v_naz noun:p:v_zna 
!   - 
                            SENT_END 

```
                        SENT_START 
```

оцінка    оцінка noun:f:v_naz 
2+  - - 
                            SENT_START 
з  з      prep:rv_rod:rv_zna:rv_oru
найкращих  хороший  adj:p:v_mis:super adj:p:v_rod:super adj:p:v_zna:super 
ресторанів    ресторан    noun:p:v_rod 
міста  місто          noun:n:v_rod noun:p:v_naz noun:p:v_zna 
!   - 
                            SENT_END 
                            SENT_START 
Атмосфера  атмосфера      noun:f:v_naz 
приємна  приємний        adj:f:v_naz:compb 
,   - - 
кухня  кухня      noun:f:v_naz 
смачна    смачний      adj:f:v_naz:compb 
,   - - 
музика    музика        noun:f:v_naz noun:f:v_naz:anim 
... - - 
.   - - 
ну    ну        excl part 
Голівуді    - - 
)   - - 
хлопчики    хлопчик      noun:p:v_kly:anim noun:p:v_naz:anim 
,   - - 
би    би        part 
"   - - 
на    на    prep:rv_zna:rv_mis 
велику    великий adj:f:v_zna:compb 
сцену  сцена noun:f:v_zna 
"   - - 
... - - 
назва  назва noun:f:v_naz 
гурту  гурт noun:m:v_dav noun:m:v_mis noun:m:v_rod 
VIP - - 
відповідає    відповідати verb:pres:s:3:imperf 
статусу  статус noun:m:v_dav noun:m:v_mis noun:m:v_rod 
                                            SENT_START 
святкували    святкувати verb:past:p:imperf 
рочок  рочок noun:m:v_naz noun:m:v_zna 
ому  ом noun:m:v_dav noun:m:v_mis 
синочкові  синочок noun:m:v_dav:anim noun:m:v_mis:anim 
!   - 
                                    SENT_END 

```
                            SENT_START 
```

готувалася    готуватися verb:rev:past:f:imperf 
свята  святий свято adj:f:v_naz:compb noun:n:v_rod noun:p:v_naz 
,   - - 
обирала  обирати verb:past:f:imperf 
ресторан    ресторан noun:m:v_naz 
,   - - 
пошкодувала  пошкодувати verb:past:f:perf 
!   - 
                                SENT_END 
                    SENT_START 
прийшли  прийти verb:past:p:perf 
,   - - 
дізнаватися  дізнаватися verb:rev:inf:imperf 
,   - - 
мали    мати verb:past:p:imperf 
розмову  розмова noun:f:v_zna 
мужчиною    мужчина noun:f:v_oru:bad:anim 
,   - - 
запевнив    запевнити verb:past:m:perf 
,   - - 
буде    бути verb:futr:s:3:imperf 
,   - - 
розповів    розповісти verb:past:m:perf 
меню    меню noun:n:v_dav:nv noun:n:v_mis:nv 
,   - - 
музику    музика noun:f:v_zna noun:f:v_zna:anim 
,   - - 
ми    ми pron:pers:p:1:v_naz:anim
залишили    залишити verb:past:p:perf 
завдаток    завдаток noun:m:v_naz noun:m:v_zna 
.   - 
                SENT_END 
                SENT_START 
2   2 number 
тижні  тиждень noun:m:v_mis noun:p:v_naz 
прийшли  прийти verb:past:p:perf 
скласти  скласти verb:inf:perf 
меню    меню noun:n:v_dav:nv 
,   - - 
мали    мати verb:past:p:imperf 
розмову  розмова noun:f:v_zna 
другим    другий adj:m:v_oru 
мужчиною    мужчина noun:f:v_oru:bad:anim 
,   - - 
взагалі  взагалі adv:v-u 
співав    співати verb:past:m:imperf 
пташка    пташка noun:f:v_naz:anim 
до    до    prep:rv_rod 
,   - - 
мала    малий мати adj:f:v_naz:compb verb:past:f:imperf 
хання  - - 
,   - - 
банально    банально adv:compb 
прикрасити    прикрасити verb:inf:perf 
зал  зал зала noun:m:v_naz noun:m:v_zna noun:p:v_rod 
,   - - 
дитячими    дитячий adj:p:v_oru 
дрібничками  дрібничка noun:p:v_oru 
,   - - 
відповіли  відповісти verb:past:p:perf 
... - 
                        SENT_END 
                        SENT_START 
тиждень  тиждень noun:m:v_naz noun:m:v_zna 
прийшли  прийти verb:past:p:perf 
,   - - 
уточнити    уточнити verb:inf:perf 
точну  точний adj:f:v_zna:compb 
кількість  кількість noun:f:v_naz noun:f:v_zna 
людей  люди noun:p:v_rod:anim noun:p:v_zna:anim 
,   - - 
мали    мати verb:past:p:imperf 
мову    мова noun:f:v_zna 
третьою  третій adj:f:v_oru 
особою    особа noun:f:v_oru:anim 
,   - - 
була    булий бути adjp:actv:past:f:v_naz verb:past:f:imperf 
жінка  жінка noun:f:v_naz:anim 

---

директор    директор noun:m:v_naz:anim 
.   - 
                    SENT_END 
                    SENT_START 
Дуже    дуже дужий adv adj:n:v_naz:compb 
гарно  гарно adv:compb 
спілкувалася    спілкуватися verb:rev:past:f:imperf 
,   - - 
наголосила    наголосити verb:past:f:perf 
,   - - 
стіл    стіл noun:m:v_naz noun:m:v_zna 
був  бути verb:past:m:imperf 
тележному  - - 
кінці  кінець noun:m:v_mis 
залу    зал зала noun:m:v_dav 
музикантів    музикант noun:p:v_rod:anim noun:p:v_zna:anim 
,   - - 
м  м noun:m:v_dav:nv:abbr 
нькі    - - 
діти    діти noun:p:v_kly:anim
... - 
                    SENT_END 
                    SENT_START 
Отприйшов  - - 
день    день noun:m:v_naz 
,   - - 
святкування  святкування noun:n:v_naz 
,   - - 
приїхала    приїхати verb:past:f:perf 
прикрасити    прикрасити verb:inf:perf 
зал  зал зала noun:m:v_naz 
,   - - 
тикали    тикати verb:past:p:imperf 
,   - - 
,   - - 
... - - 
питання- -  
!   - 
                        SENT_END 
                        SENT_START 
розмову  розмова noun:f:v_zna 
адміністратором  адміністратор oun:m:v_oru:anim 
,   - - 
встрявала  встрявати verb:past:f:imperf:v-u 
прибиральниця  прибиральниця noun:f:v_naz:anim 
,   - - 
горем  горе noun:n:v_oru 
полам  пола noun:p:v_dav 
,   - - 
прикрасила    прикрасити verb:past:f:perf 

## зал  зал зала noun:m:v_naz 

половину    половина noun:f:v_zna 
прикрас  прикраса noun:p:v_rod 
,   - - 
куплених    куплений adjp:pasv:past:p:v_misadjp:pasv:past:p:v_rod
гроші  гроші гріш noun:p:v_naz noun:p:v_zna noun:m:v_mis 
,   - - 
забрала  забрало забрати noun:n:v_rod noun:p:v_naz noun:p:v_zna verb:past:f:perf 
додому    додому adv 
!   - - 
=   - - 
(   - - 
Прийшли  прийти verb:past:p:perf 
18  18 number 
год  - - 
.   - 
                SENT_END 
                SENT_START 
був  бути verb:past:m:imperf 
забитий  забитий adjp:pasv:past:m:v_nazadjp:pasv:past:m:v_zna
зал  зал зала noun:m:v_naz noun:m:v_zna 
,   - - 
ше    - - 
,   - - 
годину    година noun:f:v_zna 
сь    - - 

## гості  гостя гість noun:f:v_dav:anim 

дозволяли  дозволяти verb:past:p:imperf 
співати  співати verb:inf:imperf 
сь    - - 
народні  народний adj:p:v_naz adj:p:v_zna 
пісні  пісний пісня adj:p:v_naz adj:p:v_zna noun:f:v_dav 
,   - - 
залі    зал зала noun:m:v_mis noun:f:v_dav noun:f:v_mis 
,   - - 
адміністратору    адміністратор noun:m:v_dav:anim noun:m:v_mis:anim 
,   - - 
би    би part 
!   - 
                    SENT_END 
                    SENT_START 
кульмінація  кульмінація noun:f:v_naz 
вечора    вечір noun:m:v_rod 
,   - - 
виходять    виходити verb:pres:p:3:imperf 
музиканти  музикант noun:p:v_kly:anim noun:p:v_naz:anim 
,   - - 
де    де adv:&pron:int:rel part 
думаєте  думати verb:pres:p:2:imperf 
стають    ставати verb:pres:p:3:imperf 
грати  грати verb:inf:imperf 
,   - - 
б  б part

**Comment by KhrystynaRybchak** [comment]
Дуже дякую!!!

**Comment by AnnaPopovich** [comment]
Добрий вечір. Файли в гілці Вікторії Паляниці також в неправильному кодуванні.

**Comment by anrom7** [comment]
погляньте тепер

**Comment by MyronYaryna** [comment]
Доброго дня. Підскажіть, будь ласка, що робити у випадку з на жаль чи
правильно я зробила записавши правильний варіант в дужки, і що робити якщо
слово офіціант не розпізналося

Мені                         я noun:s:v_dav:anim:&pron:pers:1

на                         на        prep:rv_zna:rv_mis

Нажаль( на жаль)     нажаль insert:bad

Не не part

Пощастило пощастити verb:past:n:perf

З з prep:rv_oru
Офіціантом - -
, - -
Але але conj:coord
Загалом              загалом   adv

Пристойно пристойно adv
. - PARA_END

2015-10-10 22:34 GMT+03:00 anrom7 notifications@github.com:

**Comment by OlenaStetskiv** [comment]
Добрий день! 
Шепелевич
файли Shepelevych_morph.txt та  Shepelevych_morph_without_h.txt - в неправильному кодуванні :(
Рятуйте!
Дякую)

**Comment by OksanaZvarych** [comment]
Добрий день. У мене виникли проблеми з перевіркою файлу Гентош. Оскільки вона проаналізувала лише повнозначні слова, важко визначити правильний відмінок та основу, чи доцільно вважати її варіан правильним??

**Comment by OliaTurchyniak** [comment]
Добрий вечір. Скажіть, будь ласка, яку попередницю брати, якщо немає 19-го номеру і 20-го.

**Comment by anrom7** [comment]
Доброий день.
Якщо у вашій групі 20 студентів то у сусідній напевно менше. 16? Якщо так, то беріть 17 і 18 з сусідньої групи.

**Comment by OksanaSviliak** [comment]
Доброї ночі! Файли в гілці Катерини Турянської в неправильному кодуванні. Дякую!

**Comment by anrom7** [comment]
До чого тут дякую? Подивіться тепер
