### ISSUE TITLE
Етап 2

### ISSUE THREAD

**Issue by NastiaBurdyko** [anrom7/CL_project_2015#11]
Підкажіть будь ласка де знайти файли другого етапу Ананевич Ірини. Бо в неї в гілці лише файли до першого етапу.

**Comment by anrom7** [comment]
Ананевич не витримала навантаження і покинула навчання. Файли беріть Герич

14 жовтня 2015 р. 09:51 Burdyko Anastasiia notifications@github.com
написав:
