### ISSUE TITLE
курсова 3-ій етап

### ISSUE THREAD

**Issue by Iryna-Lipkovska** [anrom7/CL_project_2015#13]
Добрий день!
Я роблю 3-ій етап курсової. В мене слово без синоніма "аналог", що з ним робити?
З повагою,
Ліпковська Ірина

**Comment by anrom7** [comment]
звідки у вас взялося слово аналог?
![image](https://cloud.githubusercontent.com/assets/1838326/10870178/f0fd8c64-80cc-11e5-810d-e1d2d7defd3c.png)

**Comment by Iryna-Lipkovska** [comment]
))) перепутала, дякую!
