### ISSUE TITLE
Етап 4

### ISSUE THREAD

**Issue by KhrystynaRybchak** [anrom7/CL_project_2015#14]
Добрий день!

Є кілька питань до четвертого етапу.
1. Чи враховувати кілька простих речень, які є частиною ще більшого складного? Наприклад: 
Були вчора у Вілла Парк, погоджуюсь із попередніми коментаторами,
погоджуюсь із попередніми коментаторами, що інтер"єр дуже дивовижний
(Вихідне речення: Були вчора у Вілла Парк, погоджуюсь із попередніми коментаторами, що інтер"єр дуже дивовижний.)
2. Чи вважати беззмістовні уривки (які ніби не несуть завершену думку) "іншими синтаксичними одиницями"? Наприклад:
погоджуюсь із попередніми коментаторами, що інтер"єр
погоджуюсь із попередніми коментаторами, що 
вчора у
у Вілла
3. У словнику Sentiment treebank подвоюють варіанти не лише з крапками 
(наприклад,
кафе
кафе.), а й з комами 
('s fairly lame|179738
's fairly lame ,|179739)
Наскільки я розумію, нам теж так робити?)
4. В останньому етапі треба вставити морфологічні характеристики. Тоді були випадки, коли ми не погоджовувалися з результатом аналізатора і писали у дужках свій варіант. Що додавати тепер: варіант аналізатора, власний, обидва?

Дякую!!!

**Comment by anrom7** [comment]
1 мали б бути синтаксичні одиниці (те що є частиною речення) якщо подивитися у як зроблено в Sentiment treebank, то мені здається там також є і беззмістовні уривки. з тих прикладі я б залишив:
погоджуюсь із попередніми коментаторами, що інтер"єр
у Вілла

2 вам теж так робити
3 обидва
