### ISSUE TITLE
Stage 6

### ISSUE THREAD

**Issue by anrom7** [anrom7/CL_project_2015#15]
Опис шостого етапу та вимоги до оформлення пояснювальної записки подано у вказівках до курсової роботи і додано в папку Stage 6 гілки Romanyuk(examples)

**Comment by KhrystynaPolishchuk** [comment]
Добрий день,
В нас буде лекція та практичні 05.12.15?
05.12.2015ПараДисциплінаВикладачКорп.Ауд.1Третя іноземна мова, частина 1
(практична)Вакансія А.А.IV н.к.1162Третя іноземна мова, частина 1
(практична)Вакансія А.А.IV н.к.1163Комп`ютерна лінгвістика (лекція)Вакансія
А.А.IV н.к.1164Комп`ютерна лінгвістика (лабораторна)Вакансія А.А.IV
н.к.1165Комп`ютерна
лінгвістика (лабораторна)Вакансія А.А.IV н.к.116
З повагою
Христина Поліщук

2015-11-29 22:25 GMT+02:00 anrom7 notifications@github.com:

**Comment by anrom7** [comment]
так

30 листопада 2015 р. 15:20 KhrystynaPolishchuk notifications@github.com
написав:

**Comment by AnnaLuno** [comment]
Добрий вечір!
Скажіть, будь ласка, чи потрібно на git hub закидувати звіт без коду програми, чи вже на екзамен видрукувати і принести звіт разом з кодом програми?

**Comment by anrom7** [comment]
тещо в шостому вказано +код на гітхаб. пояснювальну записку на іспит

19 грудня 2015 р. о 23:26 Anna Luno notifications@github.com написав:
