### ISSUE TITLE
Робота

### ISSUE THREAD

**Issue by anrom7** [anrom7/CL_project_2015#19]
http://envionsoftware.com/careers/vacancies/kharkiv?vacancy_id=56 Проводитимуть 2-тижневий курс Python у Львові, найкращого візьмуть на роботу.

**Comment by KhrystynaRybchak** [comment]
Добрий день!
Бачу у вакансіях NLI, але інформацію про курси не можу знайти. Підкажіть, будь ласка, як більше про то дізнатися)
Дякую!

**Comment by anrom7** [comment]
Пишете до цієї пані
https://www.linkedin.com/profile/view?id=AB4AABugW4gBhGD7z4yKCS9g2NRRHycwe9IAigI&authType=name&authToken=uoxs&trk=wonton-desktop

кажете що я вас рекомендував і розпитуєте деталі.

Успішного Нового року Вам!

31 грудня 2015 р. о 13:44 KhrystynaRybchak notifications@github.com
написав:

**Comment by KhrystynaRybchak** [comment]
Зрозуміло! 
Дуже дякую! Взаємно!
Веселих свят!!!
