### ISSUE TITLE
Характеристика дискурсу відгуків

### ISSUE THREAD

**Issue by IlonaOliinyk** [anrom7/CL_project_2015#2]
Доброї ночі)
Всього лиш 2 запитання:
1)Характеристику теж в txt кидати чи можна в doc?

2)І що там писати? Про помилки в написанні слів, про те що апострофа ніхто не ставить або ставить зірочку замість нього :), і що на розділові знаки також майже ніхто уваги не звертає?

**Comment by anrom7** [comment]
1. Як вам зручніше. Ця характеристика буде частиную пояснюючої записки до курсової робои.
2. Чи можна вважати відгуки окремим дискурсом? Якшо так то чому якщо ні то чому з прикладами.
   Які характерні особливості цього дискурсу з прикладами...
