### ISSUE TITLE
Wordlist

### ISSUE THREAD

**Issue by KhrystynaRybchak** [anrom7/CL_project_2015#3]
Добрий день!
Скажіть, будь ласка:
1) чи залишати власні назви (Львів, Україна)
2) чи зберігати всі форми слова, чи тільки одну (їжа / їжі - тільки їжа)
Дякую!

**Comment by anrom7** [comment]
1. залишати
2. якщо зберігати тільки одну то 350 слів то буде напевно 1000 слів тексту а вам ще з ним працювати і працювати. Зберігаєте всі форми слова.
